query GetPassengers {
    passengers {
        firstName
        lastName
        email
    }
}

query GetSchedules($startStationId: Int!, $endStationId: Int!, $startDate: String!, $endDate: String!, $passengers: Int!) {
    schedules(startStationId: $startStationId, endStationId: $endStationId, startDate: $startDate, endDate: $endDate, passengers: $passengers) {
        id
        departureTime
        arrivalTime
        route {
            id
            distance
            startStation {
                name
                city {
                    city
                    province
                }
            }
            endStation {
                name
                city {
                    city
                    province
                }
            }
            ticketType {
                salePrice
                discountPercentage
                ticketCategory {
                    name
                }
            }
        }
    }
}